<?php

class typeAttributV3
{
    const __default = 'CUP';
    const CUP = 'CUP';
    const REGION_ORIGINE = 'REGION_ORIGINE';
    const APPELLATION = 'APPELLATION';
    const PAYS_ORIGINE = 'PAYS_ORIGINE';
    const QUALITE = 'QUALITE';
    const DESIGNATION_REGLEMENTEE = 'DESIGNATION_REGLEMENTEE';
    const NOM_PRODUCTEUR = 'NOM_PRODUCTEUR';
    const PARTICULARITE = 'PARTICULARITE';
    const COULEUR = 'COULEUR';
    const POURCENTAGE_ALCOOL_PAR_VOLUME = 'POURCENTAGE_ALCOOL_PAR_VOLUME';
    const TYPE_BOUCHON = 'TYPE_BOUCHON';
    const TYPE_CONTENANT = 'TYPE_CONTENANT';
    const FAMILLE_VINS = 'FAMILLE_VINS';
    const POTENTIEL_GARDE = 'POTENTIEL_GARDE';
    const POTENTIEL_GARDE_ID = 'POTENTIEL_GARDE_ID';
    const TEMPERATURE_SERVICE_CELSIUS_A = 'TEMPERATURE_SERVICE_CELSIUS_A';
    const TEMPERATURE_SERVICE_CELSIUS_DE = 'TEMPERATURE_SERVICE_CELSIUS_DE';
    const PARTICULARITE_SERVICE = 'PARTICULARITE_SERVICE';
    const TEINTE = 'TEINTE';
    const INTENSITE = 'INTENSITE';
    const BULLES = 'BULLES';
    const PERSISTANCE_DES_BULLES = 'PERSISTANCE_DES_BULLES';
    const FAMILLE_AROMES_OLFACTIVES = 'FAMILLE_AROMES_OLFACTIVES';
    const ACIDITE = 'ACIDITE';
    const SUCRE = 'SUCRE';
    const TANNINS = 'TANNINS';
    const TEXTURE = 'TEXTURE';
    const CORPS = 'CORPS';
    const FAMILLES_AROMES_GUSTATIVES = 'FAMILLES_AROMES_GUSTATIVES';
    const COMMENTAIRE_DEGUSTATION_COURTE = 'COMMENTAIRE_DEGUSTATION_COURTE';
    const COMMENTAIRE_DEGUSTATION_LONGUE = 'COMMENTAIRE_DEGUSTATION_LONGUE';
    const CATEGORIE_MARKETING_LEVEL1 = 'CATEGORIE_MARKETING_LEVEL1';
    const CATEGORIE_MARKETING_LEVEL2 = 'CATEGORIE_MARKETING_LEVEL2';
    const CATEGORIE_MARKETING_LEVEL3 = 'CATEGORIE_MARKETING_LEVEL3';
    const TAUX_SUCRE = 'TAUX_SUCRE';


}
